import apiClient from './axios.config';

// 1. Add New Patient (Dynamic)
const createPatient = async (patientData) => {
  try {
    // Generate a Random UHID if one isn't provided/generated by backend
    // Backend Schema requires: uhid, name, age, gender, mobile...
    const payload = {
      uhid: `UHID-${Date.now()}`, // Temporary frontend generation
      name: `${patientData.firstName} ${patientData.lastName}`,
      age: Number(patientData.age),
      gender: patientData.gender,
      mobile: patientData.phone,
      address: patientData.address,
      bloodGroup: patientData.bloodGroup,
      guardianName: patientData.guardianName
    };

    const response = await apiClient.post('/patient/add', payload);
    return response.data;
  } catch (error) {
    throw error.response?.data || error.message;
  }
};

// 2. Get All Patients (Dynamic)
const getAllPatients = async () => {
  try {
    const response = await apiClient.get('/patient/all');
    return response.data.data; // Expecting array of patients
  } catch (error) {
    console.error("Error fetching patients", error);
    return [];
  }
};

export default {
  createPatient,
  getAllPatients
};